# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: Terraform tool installation
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'adesh-subscription(de544585-0db3-480d-911c-dd66a43a610d)'
    backendAzureRmResourceGroupName: 'rg-tfstate'
    backendAzureRmStorageAccountName: 'satfstate1986'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV3@3
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'adesh-subscription(de544585-0db3-480d-911c-dd66a43a610d)'
    
- task: TerraformTaskV3@3
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'adesh-subscription(de544585-0db3-480d-911c-dd66a43a610d)'
    